# Generated by Django 2.1.3 on 2018-11-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControllerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField(default=0, verbose_name='device_id')),
                ('device_name', models.CharField(max_length=12, unique=True, verbose_name='device_name')),
                ('category', models.ForeignKey(on_delete='PROTECT', to='raw_extractions.ControllerType', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Energy Name')),
                ('category', models.ManyToManyField(to='raw_extractions.ControllerType', verbose_name='Category')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='energy_names',
            field=models.ManyToManyField(to='raw_extractions.EnergyName', verbose_name='Energy Name'),
        ),
    ]
