# Generated by Django 2.1.3 on 2018-11-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_extractions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controllertype',
            name='category',
            field=models.CharField(max_length=50, unique=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_id',
            field=models.IntegerField(default=0, unique=True, verbose_name='device_id'),
        ),
        migrations.AlterField(
            model_name='energyname',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Energy Name'),
        ),
    ]
