# Generated by Django 2.1.3 on 2018-11-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_extractions', '0002_auto_20181121_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energyname',
            name='category',
        ),
        migrations.AddField(
            model_name='energyname',
            name='category',
            field=models.ForeignKey(default=1, on_delete='PROTECT', to='raw_extractions.ControllerType', verbose_name='Category'),
            preserve_default=False,
        ),
    ]
