# Generated by Django 2.1.3 on 2018-11-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_extractions', '0005_device_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.IntegerField(default=0, unique=True, verbose_name='Device Id')),
                ('category', models.ForeignKey(on_delete='PROTECT', to='raw_extractions.ControllerType', verbose_name='Category')),
            ],
        ),
        migrations.RemoveField(
            model_name='device',
            name='category',
        ),
        migrations.RemoveField(
            model_name='device',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='device',
            name='energy_names',
        ),
        migrations.AddField(
            model_name='subdevice',
            name='device_name',
            field=models.ForeignKey(on_delete='PROTECT', to='raw_extractions.Device', verbose_name='Device Name'),
        ),
        migrations.AddField(
            model_name='subdevice',
            name='energy_names',
            field=models.ManyToManyField(to='raw_extractions.EnergyName', verbose_name='Energy Name'),
        ),
    ]
