# Generated by Django 2.1.3 on 2018-11-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_extractions', '0006_auto_20181121_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_group',
            field=models.CharField(default='Chef-lieu', max_length=50, verbose_name='device_group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='device_str',
            field=models.CharField(default='CBC_BSM_XX', max_length=12, unique=True, verbose_name='device_str'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='device',
            name='device_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='device_name'),
        ),
    ]
