# Generated by Django 2.1.3 on 2018-11-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_extractions', '0007_auto_20181122_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdevice',
            name='device_value_history',
            field=models.FilePathField(default='', verbose_name='Value_storage_file'),
            preserve_default=False,
        ),
    ]
